CREATE DEFINER = 'root'@'localhost'
PROCEDURE refinance.GENERATE_DATES(IN REFINANCE_ID INT(5),IN FLAG int(5))
PROC_LABEL:
BEGIN

    DECLARE I int;
    DECLARE DONE int;
    DECLARE CREF_AGENCY VARCHAR(100);
    DECLARE CSCHEME varchar(100);
    DECLARE CREFI_DATE DATE;
    DECLARE CINTEREST decimal(20,2);
    DECLARE CAMOUNT decimal(20,2);
    DECLARE CFIRST_INSTALLMENT DATE;
    DECLARE CPAYMENT_CYCLE INT(5);
    DECLARE CNO_INSTALLMENTS INT(5);

    DECLARE GINST_DATE date;
    DECLARE GINST_AMT decimal(20,2);
    DECLARE GNET_OS decimal(20,2);

    DECLARE TEMPREFIDATE DATE;

    DECLARE TEMPOUTSTANDING decimal(20,2);

    DECLARE UPDATE_CURSOR CURSOR FOR
     SELECT INST_DATE,INST_AMT,NET_OS FROM temp_generate_dates ORDER BY INST_DATE;

    DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE = 1;

        SELECT  REFINANCE_AGENCY,
            SCHEME,
            REFI_DATE,
            INTEREST,
            AMOUNT,
            FIRST_INSTALLMENT,
            PAYMENT_CYCLE,
            NO_INSTALLMENTS 
       INTO CREF_AGENCY,
            CSCHEME,
            CREFI_DATE,
            CINTEREST,
            CAMOUNT,
            CFIRST_INSTALLMENT,
            CPAYMENT_CYCLE,
            CNO_INSTALLMENTS
       FROM REFINANCE_TEST 
      WHERE REFID=REFINANCE_ID;

    SET I = 1;

    SET TEMPREFIDATE = CFIRST_INSTALLMENT;

    SET TEMPOUTSTANDING = CAMOUNT;

    IF FLAG = 1 THEN

    DROP TABLE IF EXISTS TEMP_GENERATE_DATES;

    CREATE TABLE TEMP_GENERATE_DATES(
    REFID varchar(10),
    INST_DATE date,
    INST_AMT decimal(20,2),
    NET_OS decimal(20,2),
    INST_NUM int(5)
    );

    WHILE I <= CNO_INSTALLMENTS DO

        SET TEMPOUTSTANDING = TEMPOUTSTANDING - (CAMOUNT/CNO_INSTALLMENTS);

        INSERT INTO TEMP_GENERATE_DATES (REFID,INST_DATE,INST_AMT,NET_OS,INST_NUM)
        SELECT REFINANCE_ID,TEMPREFIDATE,(CAMOUNT/CNO_INSTALLMENTS),TEMPOUTSTANDING,I;

        SET TEMPREFIDATE = DATE_ADD(TEMPREFIDATE,INTERVAL CPAYMENT_CYCLE MONTH);
        SET I = I + 1;
    END WHILE;

    ELSEIF FLAG = 2 THEN

        -- CURSOR STARTS INSERTS OUTSTANDING
        OPEN UPDATE_CURSOR;
        L1:
        LOOP
            FETCH UPDATE_CURSOR INTO GINST_DATE,GINST_AMT,GNET_OS;
            IF DONE = 1 THEN
                LEAVE L1;
            END IF;

            SET TEMPOUTSTANDING = TEMPOUTSTANDING - GINST_AMT;
    
            UPDATE temp_generate_dates SET NET_OS = TEMPOUTSTANDING WHERE INST_DATE = GINST_DATE;

        END LOOP L1;
        CLOSE UPDATE_CURSOR;

        INSERT INTO INST_TABLE SELECT REFID,CREF_AGENCY,CSCHEME,CAMOUNT,CINTEREST,INST_DATE,INST_AMT,INST_NUM,NET_OS FROM TEMP_GENERATE_DATES ORDER BY INST_DATE;
        COMMIT;

        CALL CALCULATE_INTRST_INSERT(REFINANCE_ID);

    END IF;

END