CREATE DEFINER = 'root'@'localhost'
PROCEDURE refinance.PRINCIPAL_INTRST_INSERT(IN REFINANCE_ID INT(5))
BEGIN

    DECLARE I int;
    DECLARE DONE int;
    DECLARE CREF_AGENCY VARCHAR(100);
    DECLARE CSCHEME varchar(100);
    DECLARE CREFI_DATE DATE;
    DECLARE CINTEREST decimal(20,2);
    DECLARE CAMOUNT decimal(20,2);
    DECLARE CINTRESTPAYDATE date;
    DECLARE CINTRESTPAYPERIOD INT(5);
    DECLARE CFIRST_INSTALLMENT DATE;
    DECLARE CPAYMENT_CYCLE INT(5);
    DECLARE CNO_INSTALLMENTS INT(5);
    DECLARE LASTPRINCIPLEPAYDATE date;
    DECLARE CDIFFDAYS int(5);
    DECLARE CMIDDATES date;
    DECLARE CINST_AMT decimal(20,2);
    DECLARE COUTSTANDING decimal(20,2);
    DECLARE PREV_DATE date;
    DECLARE PREV_INSTAMT decimal(20,2);
    DECLARE PREV_OUTSTANDING decimal(20,2);
    DECLARE CURR_DATE date;
    DECLARE CURR_INSTAMT decimal(20,2);
    DECLARE CURR_OUTSTANDING decimal(20,2);

    DECLARE CGRAND_INT_AMT decimal(20,2);

    DECLARE TEMPCOUNT int(5);
    DECLARE TEMPINTERESTCOUNT int(5);
    DECLARE LOOPCOUNT int(5);
    DECLARE WHILELOOPCOUNT int(5);

    DECLARE NOOFDATES_CURSOR CURSOR FOR
     SELECT INST_DATE,OUTSTANDING,INST_AMT 
       FROM INST_TABLE
      WHERE INST_DATE >=  CREFI_DATE AND Inst_date < CINTRESTPAYDATE and REFID=REFINANCE_ID 
   ORDER BY INST_DATE;

    DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE = 1;

    DROP TABLE IF EXISTS ROUGH;

    CREATE TABLE ROUGH(
    AMOUNT decimal(20,2),
    STARTDATE date,
    ENDDATE DATE
    );

    SET I = 1;
    SET DONE = 0;
    SET WHILELOOPCOUNT = 0;

    SET TEMPINTERESTCOUNT=1;

    SELECT  REFINANCE_AGENCY,
            SCHEME,
            REFI_DATE,
            INTEREST,
            AMOUNT,
            INTRESTPAYDATE,
            INTRESTPAYPERIOD,
            FIRST_INSTALLMENT,
            PAYMENT_CYCLE,
            NO_INSTALLMENTS 
       INTO CREF_AGENCY,
            CSCHEME,
            CREFI_DATE,
            CINTEREST,
            CAMOUNT,
            CINTRESTPAYDATE,
            CINTRESTPAYPERIOD,
            CFIRST_INSTALLMENT,
            CPAYMENT_CYCLE,
            CNO_INSTALLMENTS
       FROM REFINANCE_TEST 
      WHERE REFID=REFINANCE_ID;

    SELECT MAX(Inst_date) INTO LASTPRINCIPLEPAYDATE FROM inst_table WHERE RefID=REFINANCE_ID;

    WHILE (CINTRESTPAYDATE<LASTPRINCIPLEPAYDATE) DO

        SET CGRAND_INT_AMT = 0;

        SELECT COUNT(1) INTO TEMPCOUNT FROM inst_table WHERE Inst_date >= CREFI_DATE AND Inst_date < CINTRESTPAYDATE and RefID=REFINANCE_ID;

        IF TEMPCOUNT=0 THEN

            SELECT DATEDIFF(CINTRESTPAYDATE,CREFI_DATE) INTO CDIFFDAYS;

            IF WHILELOOPCOUNT > 0 THEN

                SELECT MIN(OUTSTANDING) INTO CAMOUNT FROM INST_TABLE WHERE REFID=REFINANCE_ID AND INST_DATE <= CREFI_DATE;

            END IF;

            INSERT INTO INTEREST_TABLE (REFID,REFINANCE_AGENCY, SCHEME,INTRESTPAYDATE,INTEREST,INTREST_AMOUNT,INSTALLMENT_NO,INTRESTPERIOD) 
                 VALUES (REFINANCE_ID,CREF_AGENCY,CSCHEME,CINTRESTPAYDATE,CINTEREST,((CDIFFDAYS*(CINTEREST/365)*CAMOUNT)/100),TEMPINTERESTCOUNT,CDIFFDAYS);

            INSERT INTO ROUGH(AMOUNT,STARTDATE,ENDDATE) VALUES(CAMOUNT,CINTRESTPAYDATE,CREFI_DATE);

            SET TEMPINTERESTCOUNT = TEMPINTERESTCOUNT + 1;

        ELSEIF TEMPCOUNT>0 THEN

            SET LOOPCOUNT = 0;

            -- CURSOR STARTS
            OPEN NOOFDATES_CURSOR;
        L1:
            LOOP
                FETCH NOOFDATES_CURSOR INTO CMIDDATES,CINST_AMT,COUTSTANDING;
                IF DONE = 1 THEN
                    LEAVE L1;
                END IF;

            IF LOOPCOUNT = 0 THEN

                IF WHILELOOPCOUNT > 0 THEN
    
                    SET PREV_DATE = CURR_DATE;
                    SELECT MIN(OUTSTANDING) INTO CAMOUNT FROM INST_TABLE WHERE REFID=REFINANCE_ID AND INST_DATE <= CREFI_DATE;

                ELSE

                    SET PREV_DATE = CREFI_DATE;
    
                END IF;

                -- SET PREV_DATE = CREFI_DATE;

                SET CURR_DATE = CMIDDATES;
                SET CURR_INSTAMT = CINST_AMT;
                SET CURR_OUTSTANDING = COUTSTANDING;

            ELSE

                SET PREV_DATE = CURR_DATE;

                SET CURR_DATE = CMIDDATES;
                SET CURR_INSTAMT = CINST_AMT;
                SET CURR_OUTSTANDING = COUTSTANDING;

            END IF;

            SET CGRAND_INT_AMT = CGRAND_INT_AMT + ((DATEDIFF(CURR_DATE,PREV_DATE)*(CINTEREST/365)*(CURR_OUTSTANDING+CURR_INSTAMT))/100);

            INSERT INTO ROUGH(AMOUNT,STARTDATE,ENDDATE) VALUES((CURR_OUTSTANDING+CURR_INSTAMT),CINTRESTPAYDATE,CREFI_DATE);

            SET LOOPCOUNT = LOOPCOUNT + 1;

            END LOOP L1;
            CLOSE NOOFDATES_CURSOR;

            SET CGRAND_INT_AMT = CGRAND_INT_AMT + ((DATEDIFF(CINTRESTPAYDATE,CURR_DATE)*(CINTEREST/365)*(CURR_OUTSTANDING+CURR_INSTAMT))/100);

            INSERT INTO INTEREST_TABLE (REFID,REFINANCE_AGENCY, SCHEME,INTRESTPAYDATE,INTEREST,INTREST_AMOUNT,INSTALLMENT_NO,INTRESTPERIOD) 
                 VALUES (REFINANCE_ID,CREF_AGENCY,CSCHEME,CINTRESTPAYDATE,CINTEREST,CGRAND_INT_AMT,TEMPINTERESTCOUNT,DATEDIFF(CINTRESTPAYDATE,CREFI_DATE));

            SET TEMPINTERESTCOUNT = TEMPINTERESTCOUNT + 1;

            -- CURSOR ENDS

        END IF;

        SET CREFI_DATE = CINTRESTPAYDATE;
        SET CINTRESTPAYDATE = DATE_ADD(CINTRESTPAYDATE,INTERVAL CINTRESTPAYPERIOD MONTH);
        SET CREFI_DATE = DATE_ADD(CREFI_DATE,INTERVAL 1 DAY);

        SET WHILELOOPCOUNT = WHILELOOPCOUNT + 1;

    END WHILE;
   
END